// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: api/proto/service.proto

package urlshorter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// URLshorterClient is the client API for URLshorter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLshorterClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
}

type uRLshorterClient struct {
	cc grpc.ClientConnInterface
}

func NewURLshorterClient(cc grpc.ClientConnInterface) URLshorterClient {
	return &uRLshorterClient{cc}
}

func (c *uRLshorterClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/urlshorter.URLshorter/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLshorterClient) Post(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/urlshorter.URLshorter/Post", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLshorterServer is the server API for URLshorter service.
// All implementations must embed UnimplementedURLshorterServer
// for forward compatibility
type URLshorterServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Post(context.Context, *PostRequest) (*PostResponse, error)
	mustEmbedUnimplementedURLshorterServer()
}

// UnimplementedURLshorterServer must be embedded to have forward compatible implementations.
type UnimplementedURLshorterServer struct {
}

func (UnimplementedURLshorterServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedURLshorterServer) Post(context.Context, *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Post not implemented")
}
func (UnimplementedURLshorterServer) mustEmbedUnimplementedURLshorterServer() {}

// UnsafeURLshorterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLshorterServer will
// result in compilation errors.
type UnsafeURLshorterServer interface {
	mustEmbedUnimplementedURLshorterServer()
}

func RegisterURLshorterServer(s grpc.ServiceRegistrar, srv URLshorterServer) {
	s.RegisterService(&URLshorter_ServiceDesc, srv)
}

func _URLshorter_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLshorterServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlshorter.URLshorter/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLshorterServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLshorter_Post_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLshorterServer).Post(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/urlshorter.URLshorter/Post",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLshorterServer).Post(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// URLshorter_ServiceDesc is the grpc.ServiceDesc for URLshorter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLshorter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urlshorter.URLshorter",
	HandlerType: (*URLshorterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _URLshorter_Get_Handler,
		},
		{
			MethodName: "Post",
			Handler:    _URLshorter_Post_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/service.proto",
}
